[server]
vm-1 ansible_host=meirambek.local ansible_user=make ansible_python_interpreter=/usr/bin/python3


DEPLOY_ENV=dev ansible-playbook -i infra/ansible/inventory.ini infra/ansible/playbook.yml --ask-become-pass