app_name: devops-platform
app_base_dir: /home/make/apps
app_dir: "{{ app_base_dir }}/{{ app_name }}"
compose_file: docker-compose.dev.yaml
backend_internal_port: 8000
nginx_host_port: 80
healthcheck_url: http://127.0.0.1/health
